### ISSUE TITLE
Unclear behaviour of maximize_quantum_search

### ISSUE THREAD

**Issue by jmiszczak** [QuantumWalks/QuantumWalk.jl#29]
I get expected_runtime as follows

dim=107 res=4.688486215021979e-14
dim=108 res=42.659085358552566
dim=109 res=42.93092522057161

The above results were generated using the attached exmaple
[ex1.txt](https://github.com/QuantumWalks/QuantumWalk.jl/files/1636552/ex1.txt)

**Comment by adamglos92** [comment]
`maximize_quantum_search` requires nonzero penalty, otherwise result close to zero are usually optimal. Correct code takes the form

```
using QuantumWalk, LightGraphs

function testMe(x)
    runtime(maximize_quantum_search(x))
end

dims = [107 108 109]

graphs = map(CompleteGraph, dims)
qss = map(x->QWSearch(CTQW(x), [1], nv(x), ceil(Int, log(nv(x)))), graphs)

map(x->print("dim=", first(x), " res=", last(x), '\n'), zip(dims, map(testMe, qss)))
```

Note `nv(x)` is jumping rate optimal for CTQW and the penalty itself equals `ceil(Int, log(nv(x)))`, which is typically a good value.
