### ISSUE TITLE
Szegedy{<:Any,<:Number} vs AbstractSzegedy

### ISSUE THREAD

**Issue by jmiszczak** [QuantumWalks/QuantumWalk.jl#30]
Why this is relevant? See: evolve in szegedy_evolution.jl

**Comment by adamglos92** [comment]
Agreed. The AbstractSzegedy in current form is overcomplicated. I will transform it in a way, that current implementation of Szegedy will be it direct concrete type (till until 0.6.2018)

**Comment by adamglos92** [comment]
The Szegedy is simplified now, only two operators are allowed
